name: Cross-platform SmokeTest

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  smoke_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # Запускаем на Ubuntu и macOS
    runs-on: ${{ matrix.os }}

    steps:
      # Шаг 1: Проверить код из репозитория.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установить Python.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write the dir
        run:
          echo $GITHUB_WORKSPACE

      # Шаг 3: Перебор всех папок и выполнение SmokeTest.
      - name: Run SmokeTest on each sample
        run: |
          # Проходим по каждой папке внутри test_samples/
          for dir in test_samples/*/; do
            echo "Running smoke test for $dir..."
            # Меняем рабочую директорию на текущую папку
            cd "$dir"
            echo $GITHUB_WORKSPACE

            # Запускаем smoke_test.py в контексте этой папки
            python ../SmokeTest/smoke_test.py
            # Выходим из папки, чтобы продолжить проверку следующей
            cd -
          done
