name: Cross-platform SmokeTest

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  smoke_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # Запускаем на Ubuntu и macOS
    runs-on: ${{ matrix.os }}

    steps:
      # Шаг 1: Проверить код из репозитория.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установить Python.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Шаг 3: Перебор всех папок и выполнение SmokeTest.
      - name: Run SmokeTest on each sample
        run: |
          mkdir -p smoke_test_logs
          for dir in test_samples/*/; do
            echo "Processing $dir"
            if [ -f "$dir/requirements.txt" ]; then
              echo "Installing dependencies for $dir"
              pip install -r "$dir/requirements.txt"
            fi

            if [ -f "$dir/main.py" ]; then
              echo "Running smoke test for $dir" | tee -a smoke_test_logs/success.log
              python SmokeTest/smoke_test.py "$dir/main.py" >> smoke_test_logs/success.log 2>&1
              if [ $? -ne 0 ]; then
                echo "Smoke test failed for $dir" | tee -a smoke_test_logs/error.log
              fi
            else
              echo "Error: main.py not found in $dir" | tee -a smoke_test_logs/error.log
            fi
          done
          
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-logs
          path: smoke_test_logs/
