on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  smoke_test:
    strategy:
      matrix:
        os: [ubuntu-latest] # Запускаем на Ubuntu
    runs-on: ${{ matrix.os }}

    steps:
      # Шаг 1: Клонируем репозиторий.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install net-tools
        run: sudo apt-get install -y net-tools


      # Шаг 3: Обновляем pip.
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER
          docker --version

      # Запускаем smoke_test.py для каждой папки
      - name: Run Smoke Tests
        run: |
          for dir in test_samples/*/; do
            echo "Running smoke test for $dir..."
            export GITHUB_WORKSPACE=$dir

            PORT=8080

            # Остановка и удаление контейнеров, использующих порт
            if docker ps -q --filter "publish=$PORT" | grep .; then
              echo "Stopping Docker container using port $PORT..."
              docker stop $(docker ps -q --filter "publish=$PORT") || true
            fi

            # Проверка и освобождение порта
            if netstat -tuln | grep ":$PORT "; then
              echo "Port $PORT is in use. Freeing it..."
              fuser -k $PORT/tcp || true
            else
              echo "Port $PORT is free."
            fi

            
            if ! python SmokeTest/smoke_test.py; then
              echo "Smoke test failed for $dir"
            fi
          done
        continue-on-error: true
