name: Cross-platform SmokeTest

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  smoke_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # Запускаем на Ubuntu и macOS
    runs-on: ${{ matrix.os }}

    steps:
      # Шаг 1: Проверить код из репозитория.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установить Python.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write the dir
        run:
          echo $GITHUB_WORKSPACE

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Docker (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker
          docker --version

      - name: Install Docker (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          # Даем время, чтобы Docker открылся
          sleep 20
          docker --version


      # Шаг 3: Перебор всех папок и выполнение SmokeTest.
      - name: Run SmokeTest on each sample
        run: |
          # Проходим по каждой папке внутри test_samples/
          for dir in test_samples/*/; do
            echo "Running smoke test for $dir..."
            # Устанавливаем переменную окружения для текущей папки
            export GITHUB_WORKSPACE=$dir
            # Запускаем smoke_test.py для каждой папки
            python SmokeTest/smoke_test.py
          done
